# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lib/staged_event/event_envelope.proto

require 'google/protobuf'

require 'google/protobuf/any_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("lib/staged_event/event_envelope.proto", :syntax => :proto3) do
    add_message "staged_event.EventEnvelope" do
      optional :event, :message, 1, "google.protobuf.Any"
      optional :uuid, :string, 2
    end
  end
end

module StagedEvent
  EventEnvelope = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("staged_event.EventEnvelope").msgclass
end
