# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lib/staged_event/message_envelope.proto

require 'google/protobuf'

require 'google/protobuf/any_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("lib/staged_event/message_envelope.proto", :syntax => :proto3) do
    add_message "staged_event.MessageEnvelope" do
      optional :message, :message, 1, "google.protobuf.Any"
    end
  end
end

module StagedEvent
  MessageEnvelope = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("staged_event.MessageEnvelope").msgclass
end
